# .scrutinizer.yml
filter:
    excluded_paths: [vendor/*, test/*]


checks:
    php:
        code_rating: true
        duplication: true


build:
    environment:
        php:
            version: 5.6.9

    dependencies:
        before:
            -
                command: "mkdir build"


    tests:
        override:
            -
                command: "phpunit --configuration .phpunit.xml"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
