# .scrutinizer.yml
build:
    environment:
        php:
            version: 5.6       # Common versions: 5.4, 5.5, 5.6, 7.0, 7.1, or hhvm

    dependencies:
        before:
            -
                command: "mkdir build"

        after:
            - "composer require --dev phpunit/phpunit"

    tests:
        override:
            -
                command: "phpunit --configuration .phpunit.xml"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"

checks:
    php:
        code_rating: true
        duplication: true


filter:
    excluded_paths: [vendor/*, test/*]
